name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy2tencent:
    environment: production-tencent
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Trigger coding.net building process
        run: |
          curl -u ${{secrets.CODING_TOKEN}} \
            -v -X POST  '${{secrets.TRIGGER_URL}}' \
            -H 'Content-Type: application/json' \
            -d '
              {
              "ref": "main",
              "envs": [
                  {
                      "name": "COS_BUCKET_NAME",
                      "value": "${{secrets.BUCKET_NAME}}",
                      "sensitive": 0
                  },
                  {
                      "name": "COS_BUCKET_REGION",
                      "value": "ap-shanghai",
                      "sensitive": 0
                  },
                  {
                      "name": "COS_UPLOAD_FROM_PATH",
                      "value": "./public/",
                      "sensitive": 0
                  }
                ]
              }'
